// Project Euler : Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// Starting with 1 and 2 not exceeding 4 million find the sum of the even-valued terms.

package main

import "fmt"

func main() {
  var sum int

  first := 1
  second := 2

  if (first % 2 == 0) {
    sum += first
  }

  if (second % 2 == 0) {
    sum += second
  }

  fib(first, second, 4000000, &sum)

  fmt.Printf("The final sum is: %v\n", sum)
}

func fib(first int, second int, max int, sum *int) {
  if (second <= max) {
    temp := first + second

    if (temp % 2 == 0) {
      *sum += temp
    }

    fib(second, temp, max, sum)
  } else {

  }
}
